version: 2

models:
  - name: customer_addresses_gold
    description: Customer addresses
    columns:
      - name: customer_id
        type: int
        tests:
          - unique
          - not_null
      - name: customer_name
        type: varchar
        length: 255
      - name: state
        type: varchar
        length: 50
      - name: city
        type: varchar
        length: 50
      - name: postcode
        type: varchar
        length: 20
      - name: street
        type: varchar
        length: 255
      - name: region
        type: varchar
        length: 50
      - name: district
        type: varchar
        length: 50
      - name: lon
        type: decimal
        scale: 8
        precision: 11
      - name: lat
        type: decimal
        scale: 8
        precision: 11